### ISSUE TITLE
fstab is 404 Not Found..........

### ISSUE THREAD

**Issue by 4mond** [csmart/custom-initramfs#2]
I ran it as described in the README.txt

root@ubuntu:~/test/custom-initramfs# ./create_initramfs.sh --arch arm --dir "${PWD}" --tty ttyAMA0
Downloading busybox...
Downloading init scripts...
Downloading system files...
Failed to download the system scripts

I found that there is a problem with fstab_url = "https://raw.githubusercontent.com/buildroot/buildroot/master/system/skeleton/etc/fstab" in create_initramfs.sh file.
When I connected to the URL, I got a 404 Not found message and other URLs were able to connect normally.

Could this be an error message because of this?

How would you like to solve this? If you know anything, please answer me.

**Comment by moralrebuild** [comment]
same issue for me. What a pity for this broken script!

**Comment by eugulixes** [comment]
It should have been closed by https://github.com/csmart/custom-initramfs/commit/1068be889b2b0252afc4f172a57aef05c6a590dc.

**Comment by csmart** [comment]
Sorry, I didn't see this issue! :disappointed:
